apiVersion: rbac.authorization.k8s.io/v1
# This cluster role allows group members read access only
kind: ClusterRoleBinding
metadata:
  name: reader
subjects:
- kind: Group
  name: reader #is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: reader
  apiGroup: rbac.authorization.k8s.io